const cities = [
  {
    id: 'florence',
    name: 'Florence',
    country: 'Italy',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/cities/florence_img1.jpg',
    img1: 'media/cities/florence_img2.jpg',
    alt: 'Florence',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/cities/dubrovnik_img1.jpg',
    img1: 'media/cities/dubrovnik_img2.jpg',
    alt: 'Dubrovnik',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'Istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/cities/istanbul_img1.jpg',
    img1: 'media/cities/istanbul_img2.jpg',
    alt: 'Istanbul',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'Toledo',
    name: 'Toledo',
    country: 'Spain',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/cities/toledo_img1.jpg',
    img1: 'media/cities/toledo_img2.jpg',
    alt: 'Toledo',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'Budapest',
    name: 'Budapest',
    country: 'Hungary',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/cities/budapest_img1.jpg',
    img1: 'media/cities/budapest_img2.jpg',
    alt: 'Budapest',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
];
const countries = [
  {
    id: 'Greece',
    name: 'Greece',
    country: 'Greece',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/countries/greece_img1.jpg',
    img1: 'media/countries/greece_img2.jpg',
    alt: 'Greece',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'Croatia',
    name: 'Croatia',
    country: 'Croatia',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/countries/croatia_img1.jpg',
    img1: 'media/countries/croatia_img2.jpg',
    alt: 'Croatia',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'Italy',
    name: 'Italy',
    country: 'Italy',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/countries/italy_img1.jpg',
    img1: 'media/countries/italy_img2.jpg',
    alt: 'Italy',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'France',
    name: 'France',
    country: 'France',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/countries/france_img1.jpg',
    img1: 'media/countries/france_img2.jpg',
    alt: 'France',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'Spain',
    name: 'Spain',
    country: 'Spain',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/countries/spain_img1.jpg',
    img1: 'media/countries/spain_img1.jpg',
    alt: 'Spain',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
];

const regions = [
  {
    id: 'toscana',
    name: 'Toscana',
    country: 'Italy',
    info: 'The magnificent city of Florence is a synonym for art, beauty, and love.',
    img: 'media/regions/toscana_img1.jpg',
    img1: 'media/regions/toscana_img2_1.jpg',
    alt: 'Toscana',
    link: 'https://www.discovertuscany.com/what-to-do-in-tuscany/',
  },
  {
    id: 'dalmat',
    name: 'Dalmatia',
    country: 'Croatia',
    info: 'Top region in Italy',
    img: 'media/regions/dalmat_coast1.jpg',
    img1: 'media/regions/dalmat_coast2.jpg',
    alt: 'Dalmat Coast',
    link: 'http// activities in toscana',
  },
  {
    id: 'thassos',
    name: 'Thassos',
    country: 'Greece',
    info: 'Top region in Italy',
    img: 'media/regions/Thassos_img1.jpg',
    img1: 'media/regions/Thassos_img2.jpg',
    alt: 'Thassos',
    link: 'http// activities in toscana',
  },
  {
    id: 'alps',
    name: 'Alps',
    country: 'Italy',
    info: 'Top region in Italy',
    img: 'media/regions/alpi_img1.png',
    img1: 'media/regions/alpi_img2.jpg',
    alt: 'Alps',
    link: 'http// activities in toscana',
  },
  {
    id: 'corsica',
    name: 'Corsica',
    country: 'France',
    info: 'Top region in Italy',
    img: 'media/regions/corsica_img1.jpg',
    img1: 'media/regions/corsica_img2.jpg',
    alt: 'Corsica',
    link: 'http// activities in toscana',
  },
];
